#!/usr/bin/python3
# -*- coding: utf-8; tab-width: 4; indent-tabs-mode: t -*-

import os
import sys
import shutil
import tempfile
import argparse
sys.path.append('/usr/lib64/conduit-daemon')
from c_util import CUtil
from c_param import CConst
from c_param import CParam
from c_daemon import CDaemon


# parse parameter
parseResult = None
if True:
    argParser = argparse.ArgumentParser()
    argParser.add_argument("--port", help="Specify port for control protocol.")
    argParser.add_argument("--pid-file", dest='pid_file', help="Specify location of a PID file.")
    argParser.add_argument("-d", "--debug-level", dest='debug_level',
                           choices=['CRITICAL', 'ERROR', 'WARNING', 'INFO', 'DEBUG'], default="INFO",
                           help="Set output debug message level")
    parseResult = argParser.parse_args()

param = CParam()
try:
    # fill CParam according to argument
    if parseResult.port is not None:
        param.ctrlPort = parseResult.port
    if parseResult.pid_file is not None:
        param.pidFile = parseResult.pid_file
    param.logLevel = parseResult.debug_level

    # create logDir
    CUtil.ensureDir(param.logDir)

    # create tmpDir
    param.tmpDir = tempfile.mkdtemp(prefix="conduit-daemon-")
    CUtil.chown(param.tmpDir, CConst.user, CConst.group)

    # start server
    CDaemon(param).run()
finally:
    if param.tmpDir is not None and os.path.exists(param.tmpDir):
        shutil.rmtree(param.tmpDir)
    if os.path.exists(CConst.runDir):
        shutil.rmtree(CConst.runDir)
